### ISSUE TITLE
error: couldn't connect to server

### ISSUE THREAD

**Issue by Pawel123S** [zoldur/Ultranatum#1]
Could you help me?
I dont know what is wrong. The server is updated, and my first server is working good.
This is my second virtual machine.
<img width="776" alt="zrzut ekranu 2018-06-16 o 11 34 09" src="https://user-images.githubusercontent.com/40315595/41497643-5d31d83e-7159-11e8-9b48-5ee2c106b15b.png">

**Comment by zoldur** [comment]
That was an issue with a 3rd party. All fixed now.
